---
- name: Checkout Git Repository and Build Docker Image
  hosts: localhost

  vars:
    docker_registry: "gyanev84"
    docker_image_name: "python-app"
    docker_image_tag: "v.0.2"
    python_app_dir: "/app"
  
  tasks:
    - name: Checkout Git Repository
      ansible.builtin.git:
        repo: git@github.com:georgiyanev/DevOps-Upskill-23.git
        dest: python_app_dir

    - name: Build image and with build args
      community.docker.docker_image:
        name: docker_image_name
        build:
          path: /app/docker-image
          args:
            log_volume: /var/log/myapp
            listen_port: 8080
        source: build
    # - name: Build Docker Image
    #   command: >
    #     docker build -t {{ docker_registry }}/{{ docker_image_name }}:{{ docker_image_tag }} .
    #   args:
    #     chdir: "{{ python_app_dir }}/docker-image"
    #   become: yes
    #   when: git_checkout_result.changed
