---
- name: Checkout Git Repository and Build Docker Image
  hosts: localhost

  vars:
    docker_registry: "gyanev84"
    docker_image_name: "python-app"
    docker_image_tag: "v.0.2"
    python_app_dir: "/app"
  
  tasks:
    # - name: Checkout Git Repository
    #   ansible.builtin.git:
    #     repo: git@github.com:georgiyanev/DevOps-Upskill-23.git
    #     dest: python_app_dir

    - name: Build image and with build args
      community.docker.docker_image:
        name: docker_image_name
        build:
          path: /Dockerfile
          args:
            log_volume: /var/log/docker_image_name
            listen_port: 5001
        source: build

    - name: Tag and push to local registry
      community.docker.docker_image:
        name: docker_image_name
        repository: localhost:5000/docker_image_name
        tag: docker_image_tag
        push: true
        source: local
