---
- name: Checkout Git Repository and Build Docker Image
  hosts: localhost

  vars:
    docker_registry: "gyanev84"
    docker_image_name: "python-app"
    docker_image_tag: "v.0.2"
    python_app_dir: "/app"
  
  tasks:
    - name: Clone Git Repository
      community.general.github_repo:
        name: "https://github.com/georgiyanev/DevOps-Upskill-23.git"
        dest: "/app"
        version: "feat--ansible-homework"
        username: georgiyanev
        password: password
      register: result

    - name: Build Docker Image
      command: >
        docker build -t {{ docker_registry }}/{{ docker_image_name }}:{{ docker_image_tag }} .
      args:
        chdir: "{{ python_app_dir }}/docker-image"
      become: yes
      when: git_checkout_result.changed
