---
- name: Checkout Git Repository and Build Docker Image
  hosts: localhost

  vars:
    docker_registry: "gyanev84"
    docker_image_name: "python-app"
    docker_image_tag: "v.0.2"
    python_app_dir: "/app"
  
  tasks:
    - name: Checkout Git Repository
      ansible.builtin.git:
        repo: 'https://github.com/georgiyanev/DevOps-Upskill-23.git'
        dest: /srv/checkout
        version: docker_image_tag

    - name: Build Docker Image
      command: >
        docker build -t {{ docker_registry }}/{{ docker_image_name }}:{{ docker_image_tag }} .
      args:
        chdir: "{{ python_app_dir }}/docker-image"
      become: yes
      when: git_checkout_result.changed
