- name: Build Docker container and push it to DockerHub repository
  hosts: localhost
  gather_facts: no

  vars:
    image_name: "gyanev84/ansible-homework"
    image_tag: "v.0.2"
    ports_map: "5000:5000"
    build_dir: "/tmp/docker_build"
    cnt_name: "devops-ansible"
    docker_repo: "gyanev84/ansible-homework"
    file_owner: "root"
    file_group: "root"
    file_mode: "0777"

  tasks:
    - name: Create build directory for the Docker image
      ansible.builtin.file:
        path: "{{ build_dir }}"
        state: directory
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "{{ file_mode }}"

    - name: Copy files to build directory
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ build_dir }}/{{ item.dest }}"
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "{{ file_mode }}"
      with_items:
        - { src: "./Dockerfile", dest: "Dockerfile" }
        - { src: "./requirements.txt", dest: "requirements.txt" }
        - { src: "./app", dest: "" }

    - name: Build container image
      ansible.builtin.docker_image:
        name: "{{ image_name }}:{{ image_tag }}"
        source: build
        build:
          path: "{{ build_dir }}"
        state: present

    - name: Start the container based on that image
      ansible.builtin.docker_container:
        name: "{{ cnt_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "{{ ports_map }}"

    - name: Tag the compiled Docker image and push it to the DockerHub public repository
      ansible.builtin.docker_image:
        name: "{{ docker_repo }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local
