---
- name: Build, Push, and Run Python Docker Image
  hosts: localhost
  gather_facts: no
  become: yes

  vars:
    image_name: "georgiyanev/DevOps-Upskill-23"
    image_tag: "v0.1"
    listen_port: "5001"
    code_directory: "/code"
    app_host: "0.0.0.0"

  tasks:
    - name: Create code dir
      file:
        dest: "{{ code_directory }}"
        state: directory

    - name: Get latest app from GitHub
      git:
        repo: "git@github.com:{{ image_name }}"
        version: main
        dest: "{{ code_directory }}"
        clone: yes
        recursive: yes
        force: yes
        accept_hostkey: yes
        key_file: "/home/gyanev/.ssh/id_rsa"

    - name: Install Python libs
      pip:
        chdir: "{{ code_directory }}/requirements.txt"
        requirements: "requirements.txt"
        state: present
        virtualenv_command: "pyenv"

    - name: Start the Flask app
      shell: "flask run -h {{ app_host }} -p {{ listen_port }} &"
      args:
        chdir: "{{ code_directory }}../app"
