apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: gyanev84/github-actions:0e597cca9e5ffcde983d5eb1b8d70488acdf7bfe
          ports:
            - containerPort: 80
