apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: gyanev84/github-actions:0b144058e145e6a349062f1f420cf625878be1df
          ports:
            - containerPort: 80
