name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-18-159-112-207.eu-central-1.compute.amazonaws.com/ '

              cd / &&
              git checkout dev &&
              cd var/www/html/DevOps-Upskill-23/kubernetes/ &&
              . update-deployment.sh
              '
