name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and run script
        run: |
          bash -xv echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh.key && chmod 600 ~/.ssh.key && ssh -i ~/.ssh.key ubuntu@18.159.112.207 "/usr/sbin/hostname"
