name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 and run script
      run: |
        ssh -i /home/ubuntu/.ssh ubuntu@ip-172-31-30-104 'bash -s' < /home/ubuntu/DevOps-Upskill-23/kubernetes/update-deployment.sh

