name: CI/CD Pipeline

on:
  push:
    branches:
      - "M1-4-2-CI-Practice"

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.X"]
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Code Lint and Style
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install black
          pip install -r './requirements.txt'

      - name: Check Markdown files
        uses: github/super-linter@v4
        env:
          VALIDATE_MARKDOWN: true

      - name: Code Unittest
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Check for hardcoded secrets
        uses: zricethezav/gitleaks-action@v2
        with:
          args: --path .

      - name: Execute unit-test
        run: |
          cd './app/'
          python -m unittest app_test.py

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SCA - Snyk
        uses: snyk/actions/scan@v1
        with:
          token: ${{ secrets.SNYK_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ github.sha }}

      # - name: Scan built image with Trivy
      #   run: |
      #     docker pull gyanev84/github-actions:${{ github.sha }}
      #     docker run --rm -v $(pwd):/app -w /app aquasec/trivy gyanev84/github-actions:${{ github.sha }}
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions:${{ github.sha }}
        # env:
        #   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        #   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Add CONTRIBUTORS guide
      #   run: |
      #     echo "Follow this guide" >> CONTRIBUTORS.md
      #     git add CONTRIBUTORS.md
      #     git commit -m "Add CONTRIBUTORS guide"
      #     git push

  check_vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Scan built image with Trivy
      #   run: |
      #     docker pull gyanev84/github-actions:${{ github.sha }}
      #     docker run --rm -v $(pwd):/app -w /app aquasec/trivy --exit-code 1 gyanev84/github-actions:${{ github.sha }}
